data_cfg:
  dataset_name: HNU-Gait
  dataset_root_train: ./db/HNU-Gait/light
  dataset_root_eval: ./db/HNU-Gait/light
  dataset_partition: ./datasets/HNU-Gait/HNU-Gait.json
  num_workers: 6
  data_in_use: [True, True, False, True, False, False]
  remove_no_gallery: false # Remove probe if no gallery for it
  cache: false
  test_dataset_name: HNU-Gait

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: True
  restore_hint: 14000
  save_name: event_dinov2
  sampler:
    dropout: 0.15
    batch_shuffle: false
    batch_size: 5 # GPUs number
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 116 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: NoOperation
    - type: NoOperation
    - type: Compose
      trf_cfg:
        - type: BaseRgbTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: EDINOv2
  pretrained_dinov2: ./pretrained/dinov2_vits14_pretrain.pth                   # DINOv2 Download Link: https://dl.fbaipublicfiles.com/dinov2/dinov2_vits14/dinov2_vits14_pretrain.pth
  pretrained_mask_branch: None             # ./pretrained/MaskBranch_vits14.pt pretrained_mask_branch: None or MaskBranch Download Link: https://drive.google.com/drive/folders/1zrWPUsrbCpwxoLgfom3d2irgxkBqtXqc?usp=sharing
  in_channel: 8
  image_size: 224                                                               # 448x224
  sils_size: 32                                                                 # 64x32

  EventEncoder:
    use_event_modality_prompts: True
    num_event_modality_prompts: 256


optimizer_cfg:
  lr: 0.001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.0001

scheduler_cfg:
  gamma: 0.5
  milestones: # Learning Rate Reduction at each milestones
    - 1500
    - 2500
    - 3500
    - 4500
    - 6500
    - 9500
    - 12000
  scheduler: MultiStepLR


trainer_cfg:
  find_unused_parameters: True
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 200
  with_test: false
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 1000
  save_name: event_dinov2_padding0
  sync_BN: true
  total_iter: 18000
  sampler:
    dropout: 0.0
    batch_shuffle: true
    batch_size:
      - 40 # TripletSampler, batch_size[0] indicates Number of Identity
      - 1 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 1 # fixed frames number for training
    frames_skip_num: 3
    frames_num_max: 40 # max frames number for unfixed training
    frames_num_min: 20 # min frames numbesr for unfixed traing
    sample_type: fixed_ordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    frames_all_limit: 14
    type: TripletSampler
  transform:
    - type: NoOperation
    - type: NoOperation
    - type: Compose
      trf_cfg:
        - type: BaseRgbTransform
