data_cfg:
  dataset_name: HNU-Gait
  dataset_root_train: ./db/HNU-Gait/light
  dataset_root_eval: ./db/HNU-Gait/light
  dataset_partition: ./datasets/HNU-Gait/HNU-Gait.json
  num_workers: 6
  data_in_use: [True, True, False, False, False, False]
  remove_no_gallery: false # Remove probe if no gallery for it
  cache: false
  test_dataset_name: HNU-Gait

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: True
  restore_hint: 17000
  save_name: edinov2_hnu_gait_light_sgd
  sampler:
    dropout: 0.0
    batch_shuffle: false
    batch_size: 4 # GPUs number
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 200 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: NoOperation
    - type: NoOperation


loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: EDINOv2_Gait
  train_edino: True
  pretrained_edinov2: ./pretrained/Edino.pt
  image_size: 224                                                               # 448x224
  sils_size: 32                                                                 # 64x32
  in_channel: 8
  EventEncoder:
    use_event_modality_prompts: True
    num_event_modality_prompts: 256

  Appearance_Branch:
    source_dim: 1536
    target_dim: 16
    p: 0
    softmax: False
    Relu: False
    Up: False

  Action_Branch:
    source_dim: 8
    target_dim: 16
    p: 0
    softmax: False
    Relu: False
    Up: False

  AttentionFusion:
    in_channels: 64
    squeeze_ratio: 16
    feat_len: 2

  backbone_cfg:
    type: ResNet9
    block: BasicBlock
    in_channel: 1
    channels: # Layers configuration for automatically model construction
      - 64
      - 128
      - 256
      - 512
    layers:
      - 1
      - 1
      - 1
      - 1
    strides:
      - 1
      - 2
      - 2
      - 1
    maxpool: false
  SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 16
  SeparateBNNecks:
    class_num: 31
    in_channels: 256
    parts_num: 16
  bin_num:
    - 16



optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 15000
    - 25000
    - 30000
    - 35000
  scheduler: MultiStepLR


trainer_cfg:
  find_unused_parameters: True
  enable_float16: false # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 100
  with_test: true
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 1000
  save_name: edinov2_hnu_gait_light_sgd
  sync_BN: false
  total_iter: 40000
  sampler:
    dropout: 0.0
    batch_shuffle: true
    batch_size:
      - 6 # TripletSampler, batch_size[0] indicates Number of Identity
      - 4 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 25 # fixed frames number for training
    frames_skip_num: 3
    frames_num_max: 40 # max frames number for unfixed training
    frames_num_min: 20 # min frames number for unfixed traing
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: NoOperation
    - type: NoOperation


